import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,CheckCircle2,ChevronDown,Clock3,Flame,Leaf,Minus,Plus,Search,ShoppingBag,SlidersHorizontal,Sparkles,Trash2,X,UtensilsCrossed,LockKeyhole,Pencil,LogOut,RefreshCw,AlertCircle,LayoutGrid,Pizza,Sandwich,Salad,CakeSlice,Coffee,ChefHat} from 'lucide-react';
import {api} from './api.js';
import {cartTotal,changeQuantity,money,normalizeCart} from './cart.js';

const CATEGORIES=[['All dishes',UtensilsCrossed],['Pizza',Pizza],['Burgers',Sandwich],['Bowls',Salad],['Sides',Leaf],['Desserts',CakeSlice],['Drinks',Coffee]];
const BLANK={name:'',description:'',category:'Pizza',price:'',imageUrl:'',available:true};
const HERO='https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=90';

function FoodImage({src,alt,...props}) {
  const [failed,setFailed]=useState(false);
  useEffect(()=>setFailed(false),[src]);
  return failed?<div className="image-fallback" role="img" aria-label={alt}><UtensilsCrossed size={40}/><span>Fresh from our kitchen</span></div>:<img src={src} alt={alt} onError={()=>setFailed(true)} {...props}/>;
}

function Modal({title,onClose,children,wide=false,drawer=false}) {
  const ref=useRef();
  useEffect(()=>{const d=ref.current;d.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow='';d.close();};},[]);
  return <dialog ref={ref} className={`modal ${wide?'wide':''} ${drawer?'drawer':''}`} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}>
    <div className="modal-surface"><button className="icon-button modal-close" aria-label="Close dialog" onClick={onClose}><X size={21}/></button>{children}</div>
  </dialog>;
}

function Quantity({value,onChange,name}) {
  return <div className="quantity"><button aria-label={`Decrease ${name} quantity`} onClick={()=>onChange(-1)}><Minus size={15}/></button><span aria-live="polite">{value}</span><button disabled={value>=99} aria-label={`Increase ${name} quantity`} onClick={()=>onChange(1)}><Plus size={15}/></button></div>;
}

function App() {
  const [foods,setFoods]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const [search,setSearch]=useState(''),[category,setCategory]=useState('All dishes'),[sort,setSort]=useState('featured'),[availableOnly,setAvailableOnly]=useState(false);
  const [cart,setCart]=useState(()=>{try{return normalizeCart(JSON.parse(localStorage.getItem('aerix-food-cart')||'[]'));}catch{return [];}});
  const [cartOpen,setCartOpen]=useState(false),[selected,setSelected]=useState(null),[detailLoading,setDetailLoading]=useState(false);
  const [adminOpen,setAdminOpen]=useState(false),[auth,setAuth]=useState(''),[view,setView]=useState('menu');
  const [toast,setToast]=useState(''),[quote,setQuote]=useState(null),[quoting,setQuoting]=useState(false),[quoteError,setQuoteError]=useState('');
  const toastTimer=useRef();
  const notify=message=>{setToast(message);clearTimeout(toastTimer.current);toastTimer.current=setTimeout(()=>setToast(''),3500);};
  async function loadMenu(){setLoading(true);setError('');try{setFoods(await api('/api/foods'));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{loadMenu();return()=>clearTimeout(toastTimer.current);},[]);
  useEffect(()=>{try{localStorage.setItem('aerix-food-cart',JSON.stringify(cart));}catch{/* Cart still works when storage is unavailable. */}setQuote(null);setQuoteError('');},[cart]);
  const lines=cart.map(item=>({...item,food:foods.find(f=>f.id===item.id)}));
  const validLines=lines.filter(i=>i.food),total=cartTotal(validLines),count=cart.reduce((s,i)=>s+i.quantity,0);
  const filtered=useMemo(()=>{
    const query=search.trim().toLowerCase();let list=foods.filter(f=>(category==='All dishes'||f.category===category)&&(!availableOnly||f.available)&&(!query||`${f.name} ${f.description}`.toLowerCase().includes(query)));
    if(sort==='price-asc')list.sort((a,b)=>a.price-b.price);if(sort==='price-desc')list.sort((a,b)=>b.price-a.price);if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));return list;
  },[foods,search,category,sort,availableOnly]);
  const featured=foods.find(food=>food.id==='menu-01');
  function add(food){if(!food.available)return;setCart(c=>changeQuantity(c,food.id,1));notify(`${food.name} added to your bag`);}
  function updateQty(id,delta){setCart(c=>changeQuantity(c,id,delta));}
  async function openFood(food){setSelected(food);setDetailLoading(true);try{setSelected(await api(`/api/foods/${food.id}`));}catch(e){setSelected(null);notify(e.message);}finally{setDetailLoading(false);}}
  async function review(){setQuoting(true);setQuoteError('');try{setQuote(await api('/api/cart/quote',{method:'POST',body:JSON.stringify({items:cart.map(i=>({foodId:i.id,quantity:i.quantity}))})}));}catch(e){setQuoteError(e.message);loadMenu();}finally{setQuoting(false);}}
  function openAdmin(){if(auth){setView('admin');window.scrollTo({top:0,behavior:'smooth'});}else setAdminOpen(true);}
  return <>
    <div className="announcement"><span>A little fresh. A little fire. A whole lot of flavor.</span><span>Made to order <Flame size={13}/></span></div>
    <header className="site-header"><a href="#" className="brand" onClick={e=>{e.preventDefault();setView('menu');window.scrollTo({top:0,behavior:'smooth'});}}><span className="brand-symbol"><UtensilsCrossed size={24}/></span><span>aerix<span className="brand-amp">•</span>food<small>THE NEIGHBORHOOD KITCHEN</small></span></a>
      <nav aria-label="Main navigation"><button className={view==='menu'?'nav-link active':'nav-link'} onClick={()=>{setView('menu');setTimeout(()=>document.getElementById('menu')?.scrollIntoView({behavior:'smooth'}),30);}}>Our menu</button><a href="#kitchen" className="nav-link" onClick={()=>setView('menu')}>Our kitchen</a></nav>
      <button className="cart-button" onClick={()=>setCartOpen(true)} aria-label={`Open bag, ${count} items`}><ShoppingBag size={18}/><span>Your bag</span><b>{count}</b></button>
    </header>
    {view==='admin'?<Admin foods={foods} auth={auth} onRefresh={loadMenu} notify={notify} onExit={()=>setView('menu')} onLogout={()=>{setAuth('');setView('menu');notify('You have signed out.');}} onUnauthorized={()=>{setAuth('');setView('menu');setAdminOpen(true);}}/>:<main>
      <section className="hero" aria-labelledby="hero-title"><div className="hero-copy"><div className="eyebrow"><span/> YOUR NEXT FAVORITE MEAL</div><h1 id="hero-title">Good food.<br/>Great company.<br/><em>Yours to enjoy.</em></h1><p>From the first bite to the last little crumb.<br className="desktop-break"/> Discover honest food, big flavors, and a little joy in every dish.</p><a className="primary hero-cta" href="#menu">Find your flavor <ArrowUpRight size={20}/></a><div className="hero-notes"><span><Leaf size={17}/> Fresh ingredients</span><span><Flame size={17}/> Made to order</span></div></div>
        <div className="hero-visual"><div className="hero-image"><FoodImage src={featured?.imageUrl||HERO} alt={featured?.name||'Aerix Signature Burger'} fetchPriority="high"/></div><span className="round-seal">GOOD FOOD<br/><Sparkles size={22}/><br/>GOOD MOOD</span><div className="hero-food-label"><span><small>MEET YOUR NEW FAVORITE</small><strong>{featured?.name||'Aerix Signature Burger'}</strong><span>Flame-grilled. Full of flavor.</span></span><span className="hero-price">{money(featured?.price||14.5)}</span></div><div className="hero-caption"><span className="tiny-star">✳</span> A little comfort, straight from our kitchen.</div></div>
      </section>
      <section className="promise-strip" aria-label="Our kitchen values"><span><Leaf/>Real ingredients</span><i/><span><ChefHat/>Thoughtfully prepared</span><i/><span><ShoppingBag/>Your favorites, your way</span><i/><span><UtensilsCrossed/>Something for everyone</span></section>
      <section id="menu" className="menu-section"><div className="section-heading"><div><div className="eyebrow orange">FRESH FROM THE KITCHEN</div><h2>What are you craving?</h2><p>Something comforting. Something fresh. Something just for you.</p></div><span className="menu-mark"><Sparkles size={16}/> A menu made for good moods</span></div>
        <div className="menu-controls"><div className="category-tabs" role="group" aria-label="Food categories">{CATEGORIES.map(([name,Icon])=><button key={name} className={category===name?'category active':'category'} aria-pressed={category===name} onClick={()=>setCategory(name)}><Icon size={18}/>{name}</button>)}</div>
          <label className="search-box"><Search size={19}/><input type="search" placeholder="Find your favorite dish…" aria-label="Search menu" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={15}/></button>}</label></div>
        <div className="results-bar"><span><b>{loading?'…':filtered.length}</b> delicious possibilities{category!=='All dishes'&&<> · {category}</>}</span><div><label className="available-toggle"><input type="checkbox" checked={availableOnly} onChange={e=>setAvailableOnly(e.target.checked)}/> Available now</label><label className="sort"><SlidersHorizontal size={15}/><span className="sr-only">Sort dishes</span><select aria-label="Sort dishes" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="name">Name: A–Z</option></select><ChevronDown size={14}/></label></div></div>
        {loading?<div className="food-grid" aria-label="Loading menu" aria-busy="true">{Array.from({length:6},(_,i)=><div className="skeleton-card" key={i}><div/><span/><span/></div>)}</div>:error?<div className="empty-state" role="alert"><AlertCircle/><h3>The kitchen is a moment away</h3><p>{error}</p><button className="primary" onClick={loadMenu}><RefreshCw size={17}/> Try again</button></div>:filtered.length===0?<div className="empty-state"><Search/><h3>No dishes found</h3><p>Try a different search or explore another category.</p><button className="secondary" onClick={()=>{setSearch('');setCategory('All dishes');setAvailableOnly(false);}}>Show all dishes</button></div>:<div className="food-grid">{filtered.map((food,index)=><article className={`food-card ${!food.available?'sold-out':''}`} key={food.id}><button className="food-photo" onClick={()=>openFood(food)} aria-label={`View ${food.name}`}><FoodImage src={food.imageUrl} alt={food.name} loading="lazy"/>{!food.available?<span className="food-badge muted">Back soon</span>:food.id==='menu-01'?<span className="food-badge"><Flame size={13}/> House favorite</span>:food.category==='Bowls'?<span className="food-badge green"><Leaf size={13}/> Fresh pick</span>:null}<span className="photo-arrow"><ArrowUpRight size={20}/></span></button><div className="food-card-body"><span className="food-category">{food.category}</span><button className="food-title" onClick={()=>openFood(food)}><h3>{food.name}</h3></button><p>{food.description}</p><div className="food-card-bottom"><strong>{money(food.price)}</strong><button className="add-button" disabled={!food.available} onClick={()=>add(food)} aria-label={`Add ${food.name} to bag`}><Plus size={18}/><span>{food.available?'Add to bag':'Unavailable'}</span></button></div></div></article>)}</div>}
      </section>
      <section className="kitchen-section" id="kitchen"><div className="kitchen-art"><Leaf size={70} strokeWidth={1}/><span>GOOD FOOD<br/>STARTS WITH CARE.</span></div><div><div className="eyebrow orange">A LITTLE ABOUT US</div><h2>Big on flavor.<br/>Even bigger on care.</h2><p>Aerix Food is a neighborhood kitchen built around a simple idea: everyday food should feel a little special. Fresh ingredients, comforting classics, and something delicious for every kind of craving.</p><a href="#menu" className="text-link">Find your next favorite <ArrowRight size={18}/></a></div></section>
    </main>}
    <footer><div className="footer-top"><a className="brand" href="#" onClick={()=>setView('menu')}><span className="brand-symbol"><UtensilsCrossed size={23}/></span><span>aerix<span className="brand-amp">•</span>food<small>GOOD FOOD. GOOD MOOD.</small></span></a><p>Thoughtfully made.<br/>Happily enjoyed.</p><button className="admin-link" onClick={openAdmin}><LockKeyhole size={15}/> Restaurant admin <ArrowUpRight size={15}/></button></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Aerix Food · Restaurant concept</span><span>All prices in USD · Images are illustrative</span></div></footer>
    {count>0&&!cartOpen&&view==='menu'&&<button className="mobile-bag" onClick={()=>setCartOpen(true)}><span><ShoppingBag size={18}/> View bag <b>{count}</b></span><strong>{money(total)}</strong></button>}
    {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}</div>}
    {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)} wide><div className="detail-image"><FoodImage src={selected.imageUrl} alt={selected.name}/></div><div className="detail-body"><span className="food-category">{selected.category}</span><h2>{selected.name}</h2><p>{selected.description}</p><div className="detail-note"><Leaf size={17}/> Questions about ingredients or allergens? Please ask the restaurant before ordering.</div><div className="detail-bottom"><strong>{money(selected.price)}</strong><button className="primary" disabled={!selected.available||detailLoading} onClick={()=>{add(selected);setSelected(null);}}><Plus size={18}/>{selected.available?'Add to your bag':'Currently unavailable'}</button></div></div></Modal>}
    {cartOpen&&<Modal title="Your bag" onClose={()=>{setCartOpen(false);setQuote(null);}} drawer><div className="drawer-heading"><div className="eyebrow orange">YOUR NEXT GOOD MEAL</div><h2>Your bag <span>{count}</span></h2><p>A little of what you love.</p></div>{cart.length===0?<div className="empty-cart"><ShoppingBag size={48} strokeWidth={1}/><h3>A good meal starts here</h3><p>Your bag is waiting for something delicious.</p><button className="primary" onClick={()=>{setCartOpen(false);document.getElementById('menu')?.scrollIntoView({behavior:'smooth'});}}>Explore the menu <ArrowRight size={17}/></button></div>:<><div className="cart-items">{lines.map(({id,food,quantity})=><div className="cart-item" key={id}>{food&&<FoodImage src={food.imageUrl} alt={food.name}/>}<div className="cart-item-info"><strong>{food?.name||'This item is no longer on the menu'}</strong>{food?<span>{money(food.price)} each</span>:null}{food&&!food.available&&<small className="field-error">Currently unavailable</small>}<Quantity name={food?.name||'item'} value={quantity} onChange={d=>updateQty(id,d)}/></div><div className="cart-item-end"><button className="icon-button" aria-label={`Remove ${food?.name||'item'}`} onClick={()=>setCart(c=>c.filter(i=>i.id!==id))}><Trash2 size={16}/></button><strong>{food?money(Math.round(food.price*100)*quantity/100):'—'}</strong></div></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>{money(total)}</strong></div><div className="total"><span>Total</span><strong>{money(total)}</strong></div><p>Menu prices only. Review your items before visiting the restaurant.</p>{quoteError&&<p className="error-box" role="alert">{quoteError}</p>}{quote?<div className="quote-success" role="status"><CheckCircle2/><h3>Your summary is ready</h3><p>{quote.items.reduce((s,i)=>s+i.quantity,0)} items · <strong>{money(quote.total)}</strong></p><p>Prices checked with the kitchen. This is a summary; no order or payment has been placed.</p><button className="secondary" onClick={()=>{setQuote(null);setCartOpen(false);}}>Continue browsing</button></div>:<button className="primary full" disabled={quoting||loading||lines.some(i=>!i.food||!i.food.available)} onClick={review}>{quoting?'Checking your items…':'Review order'}<ArrowRight size={18}/></button>}<button className="text-link centered" onClick={()=>setCartOpen(false)}>Add a little something else</button></div></>}</Modal>}
    {adminOpen&&<Login onClose={()=>setAdminOpen(false)} onLogin={token=>{setAuth(token);setAdminOpen(false);setView('admin');window.scrollTo(0,0);}}/>}
  </>;
}

function Login({onClose,onLogin}) {
  const [username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const token='Basic '+btoa(username+':'+password);await api('/api/admin/session',{headers:{Authorization:token}});onLogin(token);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <Modal title="Administrator sign in" onClose={onClose}><form className="login-form" onSubmit={submit}><span className="login-icon"><LockKeyhole/></span><div className="eyebrow orange">BACK OF HOUSE</div><h2>Welcome to the kitchen.</h2><p>Sign in to manage your restaurant’s menu.</p><label>Username<input autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error-box" role="alert">{error}</p>}<button className="primary full" disabled={busy}>{busy?'Signing in…':'Sign in'}<ArrowRight size={18}/></button></form></Modal>;
}

function Admin({foods,auth,onRefresh,notify,onExit,onLogout,onUnauthorized}) {
  const [editing,setEditing]=useState(null),[deleting,setDeleting]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
  const visible=foods.filter(f=>`${f.name} ${f.category}`.toLowerCase().includes(query.toLowerCase()));
  async function remove(){setBusy(true);setError('');try{await api(`/api/foods/${deleting.id}`,{method:'DELETE',headers:{Authorization:auth}});setDeleting(null);notify('Food item deleted.');await onRefresh();}catch(e){if(e.status===401)onUnauthorized();else setError(e.message);}finally{setBusy(false);}}
  return <main className="admin-page"><div className="admin-heading"><div><div className="eyebrow orange">RESTAURANT MANAGEMENT</div><h1>Your kitchen, at a glance.</h1><p>Keep your menu fresh, accurate, and ready for your guests.</p></div><button className="secondary" onClick={onLogout}><LogOut size={17}/> Sign out</button></div><div className="admin-stats"><div><span><LayoutGrid size={18}/> On the menu</span><strong>{foods.length}<small>dishes</small></strong></div><div><span><CheckCircle2 size={18}/> 
  Ready to order</span><strong>{foods.filter(f=>f.available).length}<small>available</small></strong></div><div><span><Clock3 size={18}/> Taking a break</span><strong>{foods.filter(f=>!f.available).length}<small>unavailable</small></strong></div></div><section className="admin-menu"><div className="admin-menu-heading"><div><h2>Manage your menu</h2><p>Add something new or perfect an old favorite.</p></div><button className="primary" onClick={()=>setEditing({...BLANK})}><Plus size={18}/>
   Add food item</button></div><div className="admin-toolbar"><label className="search-box"><Search size={18}/><input aria-label="Search admin menu" placeholder="Search by name or category…" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="text-link" onClick={onExit}>View customer menu <ArrowUpRight size={17}/></button></div><div className="table-scroll"><table><thead><tr><th>Food item</th><th>Category</th><th>Price</th><th>Availability</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map(f=><tr key={f.id}><td><div className="table-food"><FoodImage src={f.imageUrl} alt={f.name}/><span><strong>{f.name}</strong><small>ID: {f.id}</small></span></div></td><td>{f.category}</td><td><strong>{money(f.price)}</strong></td><td><span className={`status-pill ${f.available?'yes':'no'}`}><span/>{f.available?'Available':'Unavailable'}</span></td><td><div className="row-actions"><button className="icon-button" aria-label={`Edit ${f.name}`} onClick={()=>setEditing({...f})}><Pencil size={17}/></button><button className="icon-button danger" aria-label={`Delete ${f.name}`} onClick={()=>{setDeleting(f);setError('');}}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table>{visible.length===0&&<div className="empty-state"><Search/><h3>No matching dishes</h3><p>Add your first dish or change your search.</p></div>}</div></section>{editing&&<FoodForm food={editing} auth={auth} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);notify(editing.id?'Menu item updated.':'New dish added to your menu.');await onRefresh();}} onUnauthorized={onUnauthorized}/>}{deleting&&<Modal title="Delete food item" onClose={()=>{if(!busy)setDeleting(null);}}><div className="confirm-delete"><span className="delete-symbol"><Trash2 size={28}/></span><h2>Remove this dish?</h2><p><strong>{deleting.name}</strong> will be removed from the menu. This cannot be undone.</p>{error&&<p className="error-box" role="alert">{error}</p>}<div className="form-actions"><button className="secondary" disabled={busy} onClick={()=>setDeleting(null)}>Keep dish</button><button className="danger-button" disabled={busy} onClick={remove}>{busy?'Removing…':'Delete dish'}</button></div></div></Modal>}</main>;
}

function FoodForm({food,auth,onClose,onSaved,onUnauthorized}) {
  const [form,setForm]=useState(food),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({});
  const change=(name,value)=>{setForm(f=>({...f,[name]:value}));setFields(f=>({...f,[name]:null}));};
  async function submit(e){e.preventDefault();setBusy(true);setError('');setFields({});try{await api('/api/foods'+(food.id?'/'+food.id:''),{method:food.id?'PUT':'POST',headers:{Authorization:auth},body:JSON.stringify({...form,price:Number(form.price)})});await onSaved();}catch(e){if(e.status===401)onUnauthorized();else{setError(e.message);setFields(e.fields||{});}}finally{setBusy(false);}}
  return <Modal title={food.id?'Edit food item':'Add food item'} onClose={()=>{if(!busy)onClose();}} wide><form className="food-form" onSubmit={submit}><div className="eyebrow orange">FRESHEN UP THE MENU</div><h2>{food.id?'Make it even better.':'Something new to love.'}</h2><p>{food.id?'Update this dish’s details below.':'Add a delicious new dish for your guests to discover.'}</p><div className="form-grid"><label className="span-two">Food name<input required maxLength={80} value={form.name} onChange={e=>change('name',e.target.value)} aria-invalid={!!fields.name}/>{fields.name&&<small className="field-error">{fields.name}</small>}</label><label className="span-two">Description<textarea required maxLength={500} rows={3} value={form.description} onChange={e=>change('description',e.target.value)} aria-invalid={!!fields.description}/>{fields.description&&<small className="field-error">{fields.description}</small>}</label><label>Category<select value={form.category} onChange={e=>change('category',e.target.value)}>{CATEGORIES.slice(1).map(([c])=><option key={c}>{c}</option>)}</select></label><label>Price (USD)<input type="number" required min="0.01" max="9999.99" step="0.01" value={form.price} onChange={e=>change('price',e.target.value)} aria-invalid={!!fields.price}/>{fields.price&&<small className="field-error">{fields.price}</small>}</label><label className="span-two">Image URL<input type="url" required pattern="https://.*" placeholder="https://…" value={form.imageUrl} onChange={e=>change('imageUrl',e.target.value)} aria-invalid={!!fields.imageUrl}/><small>Use a publicly accessible HTTPS link to a food photograph.</small>{fields.imageUrl&&<small className="field-error">{fields.imageUrl}</small>}</label><label className="availability-field span-two"><input type="checkbox" checked={form.available} onChange={e=>change('available',e.target.checked)}/><span><strong>Available to order</strong><small>Turn this off when the dish is sold out.</small></span></label></div>{error&&<p className="error-box" role="alert">{error}</p>}<div className="form-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy}><Check size={18}/>{busy?'Saving…':food.id?'Save changes':'Add to menu'}</button></div></form></Modal>;
}

export default App;

